CREATE SCHEMA IF NOT EXISTS public;

DROP TABLE IF EXISTS PUBLIC.MODEL CASCADE;
CREATE TABLE IF NOT EXISTS PUBLIC.MODEL (
  ID SERIAL PRIMARY KEY,
  MODEL_NAME VARCHAR(100) NOT NULL,
  IS_DISPLAYED BOOLEAN,
  COUNTRY_ISO_A3 CHAR(3) NOT NULL
);

DROP TABLE IF EXISTS PUBLIC.MODEL_SCORES CASCADE;
CREATE TABLE IF NOT EXISTS PUBLIC.MODEL_SCORES (
  ID SERIAL PRIMARY KEY,
  IMPORT_TIMESTAMP TIMESTAMP NOT NULL,
  SCORE_DATE DATE NOT NULL,
  WEIGHTED_DEBIASED DOUBLE PRECISION NOT NULL,
  WEIGHTED DOUBLE PRECISION NOT NULL,
  HISTORICAL_TREND DOUBLE PRECISION NOT NULL,
  HISTORICAL_TREND_LOWER DOUBLE PRECISION NOT NULL,
  HISTORICAL_TREND_UPPER DOUBLE PRECISION NOT NULL,
  MODEL_ID INTEGER NOT NULL
);

DROP TABLE IF EXISTS PUBLIC.DEFAULT_MODEL CASCADE;
CREATE TABLE IF NOT EXISTS PUBLIC.DEFAULT_MODEL (
  ID SERIAL PRIMARY KEY,
  COUNTRY_ISO_A3 CHAR(3) UNIQUE NOT NULL,
  MODEL_ID INTEGER NOT NULL
);

DROP TABLE IF EXISTS PUBLIC.COUNTRY_TOTALS;
CREATE TABLE IF NOT EXISTS PUBLIC.COUNTRY_TOTALS (
  ID SERIAL PRIMARY KEY,
  COUNTRY_ISO_A3 CHAR(3) UNIQUE NOT NULL,
  CASES_PER_100K DOUBLE PRECISION NOT NULL
);

ALTER TABLE IF EXISTS PUBLIC.MODEL_SCORES
  DROP CONSTRAINT IF EXISTS FK_MODEL_MODEL_SCORES;
ALTER TABLE IF EXISTS PUBLIC.MODEL_SCORES
  ADD CONSTRAINT FK_MODEL_MODEL_SCORES
    FOREIGN KEY (MODEL_ID)
    REFERENCES PUBLIC.MODEL(ID);

ALTER TABLE IF EXISTS PUBLIC.DEFAULT_MODEL
  DROP CONSTRAINT IF EXISTS FK_MODEL_DEFAULT_MODEL;
ALTER TABLE IF EXISTS PUBLIC.DEFAULT_MODEL
  ADD CONSTRAINT FK_MODEL_DEFAULT_MODEL
    FOREIGN KEY (MODEL_ID)
    REFERENCES PUBLIC.MODEL(ID);
