CREATE SCHEMA IF NOT EXISTS public;

CREATE TABLE IF NOT EXISTS PUBLIC.MODEL (
  ID IDENTITY PRIMARY KEY,
  MODEL_NAME VARCHAR(100) NOT NULL,
  IS_DISPLAYED BOOLEAN,
  COUNTRY_ISO_A3 CHAR(3) NOT NULL
);

CREATE TABLE IF NOT EXISTS PUBLIC.MODEL_SCORES (
  ID IDENTITY PRIMARY KEY,
  IMPORT_TIMESTAMP TIMESTAMP NOT NULL,
  SCORE_DATE DATE NOT NULL,
  WEIGHTED_DEBIASED DOUBLE PRECISION NOT NULL,
  WEIGHTED DOUBLE PRECISION NOT NULL,
  HISTORICAL_TREND DOUBLE PRECISION NOT NULL,
  HISTORICAL_TREND_LOWER DOUBLE PRECISION NOT NULL,
  HISTORICAL_TREND_UPPER DOUBLE PRECISION NOT NULL
);

INSERT INTO PUBLIC.MODEL (MODEL_NAME, IS_DISPLAYED, COUNTRY_ISO_A3)
  VALUES ('MODEL1', TRUE, 'GBR');

INSERT INTO PUBLIC.MODEL_SCORES (IMPORT_TIMESTAMP, SCORE_DATE, WEIGHTED_DEBIASED,
  WEIGHTED, HISTORICAL_TREND, HISTORICAL_TREND_LOWER, HISTORICAL_TREND_UPPER)
  VALUES (LOCALTIMESTAMP, CURRENT_DATE, 0.1, 0.1, 0.1, 0.1, 0.1);