CREATE SCHEMA IF NOT EXISTS public;

DROP TABLE IF EXISTS PUBLIC.MODEL;
CREATE TABLE IF NOT EXISTS PUBLIC.MODEL (
  ID IDENTITY PRIMARY KEY,
  MODEL_NAME VARCHAR(100) NOT NULL,
  IS_DISPLAYED BOOLEAN,
  COUNTRY_ISO_A3 CHAR(3) NOT NULL
);

DROP TABLE IF EXISTS PUBLIC.MODEL_SCORES;
CREATE TABLE IF NOT EXISTS PUBLIC.MODEL_SCORES (
  ID IDENTITY PRIMARY KEY,
  IMPORT_TIMESTAMP TIMESTAMP NOT NULL,
  SCORE_DATE DATE NOT NULL,
  WEIGHTED_DEBIASED DOUBLE PRECISION NOT NULL,
  WEIGHTED DOUBLE PRECISION NOT NULL,
  HISTORICAL_TREND DOUBLE PRECISION NOT NULL,
  HISTORICAL_TREND_LOWER DOUBLE PRECISION NOT NULL,
  HISTORICAL_TREND_UPPER DOUBLE PRECISION NOT NULL,
  MODEL_ID INTEGER NOT NULL
);

DROP TABLE IF EXISTS PUBLIC.DEFAULT_MODEL;
CREATE TABLE IF NOT EXISTS PUBLIC.DEFAULT_MODEL (
  ID IDENTITY PRIMARY KEY,
  COUNTRY_ISO_A3 CHAR(3) UNIQUE NOT NULL,
  MODEL_ID INTEGER NOT NULL
);

ALTER TABLE IF EXISTS PUBLIC.MODEL_SCORES
  ADD CONSTRAINT IF NOT EXISTS FK_MODEL_MODEL_SCORES
    FOREIGN KEY (MODEL_ID)
    REFERENCES PUBLIC.MODEL(ID);

ALTER TABLE IF EXISTS PUBLIC.DEFAULT_MODEL
  ADD CONSTRAINT IF NOT EXISTS FK_MODEL_DEFAULT_MODEL
    FOREIGN KEY (MODEL_ID)
    REFERENCES PUBLIC.MODEL(ID);

INSERT INTO PUBLIC.MODEL (MODEL_NAME, IS_DISPLAYED, COUNTRY_ISO_A3)
  VALUES ('MODEL1', TRUE, 'GBR');

INSERT INTO PUBLIC.MODEL_SCORES (IMPORT_TIMESTAMP, SCORE_DATE, WEIGHTED_DEBIASED,
  WEIGHTED, HISTORICAL_TREND, HISTORICAL_TREND_LOWER, HISTORICAL_TREND_UPPER,
  MODEL_ID)
  VALUES (LOCALTIMESTAMP, CURRENT_DATE, 0.1, 0.1, 0.1, 0.1, 0.1, 1);
INSERT INTO PUBLIC.MODEL_SCORES (IMPORT_TIMESTAMP, SCORE_DATE, WEIGHTED_DEBIASED,
  WEIGHTED, HISTORICAL_TREND, HISTORICAL_TREND_LOWER, HISTORICAL_TREND_UPPER,
  MODEL_ID)
  VALUES (LOCALTIMESTAMP, CURRENT_DATE, 0.2, 0.3, 0.4, 0.5, 0.6, 1);

INSERT INTO PUBLIC.DEFAULT_MODEL (COUNTRY_ISO_A3, MODEL_ID)
  VALUES ('GBR', 1);